<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClaimRegisterSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'id' => 1,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'TED June-August 2024',
                'claim_month' => 'June -Aug',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '225000.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 16:57:32',
                'updated_at' => '2026-03-30 16:57:32',
            ],
            [
                'id' => 2,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Top Shops December 2024',
                'claim_month' => 'December',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '39675.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 16:59:25',
                'updated_at' => '2026-03-30 17:06:57',
            ],
            [
                'id' => 3,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Hospital Pharmacy December 24',
                'claim_month' => 'December',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '20000.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:01:01',
                'updated_at' => '2026-03-30 17:01:01',
            ],
            [
                'id' => 4,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'GRN-Lactogen 2 120g',
                'claim_month' => 'December',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '32243.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:04:37',
                'updated_at' => '2026-03-30 17:04:37',
            ],
            [
                'id' => 5,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Cerelac Rice 25g Free Sampling',
                'claim_month' => 'May',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '63366.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:06:25',
                'updated_at' => '2026-03-30 17:06:25',
            ],
            [
                'id' => 6,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Baby Feeding Claim (Mr.Zargam)',
                'claim_month' => 'August',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '26931.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:07:54',
                'updated_at' => '2026-03-30 17:07:54',
            ],
            [
                'id' => 7,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'NFV Sparkeling & Nescafe RTD',
                'claim_month' => 'June-July',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '48000.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:08:14',
                'updated_at' => '2026-03-30 17:08:14',
            ],
            [
                'id' => 8,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Drug Store July 2025',
                'claim_month' => 'July',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '139500.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:08:33',
                'updated_at' => '2026-03-30 17:08:33',
            ],
            [
                'id' => 9,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'DD Dsf Numeric Drive-August',
                'claim_month' => 'October',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '41475.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:08:50',
                'updated_at' => '2026-03-30 17:08:50',
            ],
            [
                'id' => 10,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Nescafe 50g Promo',
                'claim_month' => 'October',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '72000.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:09:11',
                'updated_at' => '2026-03-30 17:09:11',
            ],
            [
                'id' => 11,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Power Store Q3',
                'claim_month' => 'Q3',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '264060.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:09:40',
                'updated_at' => '2026-03-30 17:09:40',
            ],
            [
                'id' => 12,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Hospital Pharmacy Q3',
                'claim_month' => 'Q3',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '45000.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:09:59',
                'updated_at' => '2026-03-30 17:09:59',
            ],
            [
                'id' => 13,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Rate Diff Claim Juice NFV 200ml',
                'claim_month' => 'September',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '40499.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:10:16',
                'updated_at' => '2026-03-30 17:10:16',
            ],
            [
                'id' => 14,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Juice Liquidation Oct 25',
                'claim_month' => 'October',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '34500.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:10:37',
                'updated_at' => '2026-03-30 17:10:37',
            ],
            [
                'id' => 15,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'GRN-Powder october 2025',
                'claim_month' => 'October',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '6049.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:11:01',
                'updated_at' => '2026-03-30 17:11:01',
            ],
            [
                'id' => 16,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'GRN Koko Cookies Oct 25',
                'claim_month' => 'October',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '22461.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:11:20',
                'updated_at' => '2026-03-30 17:11:20',
            ],
            [
                'id' => 17,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Baby Feeding Claim (ASM)',
                'claim_month' => 'December',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '26931.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:11:48',
                'updated_at' => '2026-03-30 17:11:48',
            ],
            [
                'id' => 18,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'TTS December 2025',
                'claim_month' => 'December',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '912794.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:12:39',
                'updated_at' => '2026-03-30 17:12:39',
            ],
            [
                'id' => 19,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'GRN-Powder December 2025',
                'claim_month' => 'December',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '8945.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:12:59',
                'updated_at' => '2026-03-30 17:12:59',
            ],
            [
                'id' => 20,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Drug Store November 2025',
                'claim_month' => 'November',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '138700.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:13:20',
                'updated_at' => '2026-03-30 17:13:20',
            ],
            [
                'id' => 21,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Drug Store December 2025',
                'claim_month' => 'December',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '139500.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:13:45',
                'updated_at' => '2026-03-30 17:13:45',
            ],
            [
                'id' => 22,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Hospital Pharmacy December 25',
                'claim_month' => 'December',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '15000.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:14:04',
                'updated_at' => '2026-03-30 17:14:04',
            ],
            [
                'id' => 23,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Expension Drug Store Nov & Dec 25',
                'claim_month' => 'Nov & Dec',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '50000.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:14:30',
                'updated_at' => '2026-03-30 17:14:30',
            ],
            [
                'id' => 24,
                'supplier_id' => 3,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'TTS February 2026',
                'claim_month' => 'February',
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '974678.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:14:52',
                'updated_at' => '2026-03-30 17:14:52',
            ],
            [
                'id' => 25,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Expiry  Sept-2025',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '65298.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:36:00',
                'updated_at' => '2026-03-30 17:42:11',
            ],
            [
                'id' => 26,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Naya Jeevan Payment 2025-26',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '112050.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:36:15',
                'updated_at' => '2026-03-30 17:36:15',
            ],
            [
                'id' => 27,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Expiry  Oct-2025',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '75641.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:36:32',
                'updated_at' => '2026-03-30 17:42:17',
            ],
            [
                'id' => 28,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Expiry  Nov-2025',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '140437.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:37:00',
                'updated_at' => '2026-03-30 17:42:25',
            ],
            [
                'id' => 29,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'OB Salary Jan-26',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '114625.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:37:16',
                'updated_at' => '2026-03-30 17:44:49',
            ],
            [
                'id' => 30,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Expiry  Dec-2025',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '192698.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:37:36',
                'updated_at' => '2026-03-30 17:44:58',
            ],
            [
                'id' => 31,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'Expiry  Jan-2026',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '189231.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:37:52',
                'updated_at' => '2026-03-30 17:45:04',
            ],
            [
                'id' => 32,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'PS 1.0 UHT Drive Dec-25',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '15000.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:38:10',
                'updated_at' => '2026-03-30 17:45:13',
            ],
            [
                'id' => 33,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'PS 3.0 Renatl Oct-2025',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '60000.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:38:49',
                'updated_at' => '2026-03-30 17:45:25',
            ],
            [
                'id' => 34,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'PS 3.0 Renatl  Nov-2025',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '60000.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:39:11',
                'updated_at' => '2026-03-30 17:45:49',
            ],
            [
                'id' => 35,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'PS 3.0 Renatl  Dec-2025',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '60000.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:39:33',
                'updated_at' => '2026-03-30 17:49:10',
            ],
            [
                'id' => 36,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'PS 2.0 Renatl Oct-2025',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '63500.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:39:53',
                'updated_at' => '2026-03-30 17:49:39',
            ],
            [
                'id' => 37,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'PS 2.0 Renatl  Nov-2025',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '63500.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:41:27',
                'updated_at' => '2026-03-30 17:50:13',
            ],
            [
                'id' => 38,
                'supplier_id' => 4,
                'transaction_date' => '2026-03-30',
                'reference_number' => null,
                'description' => 'PS 2.0 Renatl  Dec-2025',
                'claim_month' => null,
                'date_of_dispatch' => null,
                'transaction_type' => 'claim',
                'debit' => '63500.00',
                'credit' => '0.00',
                'debit_account_id' => 5,
                'credit_account_id' => 116,
                'payment_method' => 'bank_transfer',
                'bank_account_id' => 1,
                'notes' => null,
                'journal_entry_id' => null,
                'posted_at' => null,
                'posted_by' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => null,
                'created_at' => '2026-03-30 17:41:51',
                'updated_at' => '2026-03-30 17:41:51',
            ],
        ];

        DB::table('claim_registers')->insert($rows);

        $driver = DB::getDriverName();

        if ($driver === 'pgsql') {
            DB::statement("SELECT setval(pg_get_serial_sequence('claim_registers', 'id'), COALESCE(MAX(id), 1)) FROM claim_registers");
        } elseif (in_array($driver, ['mysql', 'mariadb'], true)) {
            $nextId = (int) DB::table('claim_registers')->max('id') + 1;
            if ($nextId < 1) {
                $nextId = 1;
            }
            DB::statement("ALTER TABLE claim_registers AUTO_INCREMENT = {$nextId}");
        }
    }
}
