<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'name' => 'Mr. Super Admin',
                'designation' => 'Super Admin',
                'email' => 'sa@example.com',
                'password' => 'password',
                'is_super_admin' => 'Yes',
                'is_active' => 'Yes',
                'role' => 'super-admin',
                'permissions' => [],
            ],
            [
                'name' => 'Mr. Admin',
                'designation' => 'ADMIN',
                'email' => 'a@example.com',
                'password' => 'password',
                'is_super_admin' => 'No',
                'is_active' => 'Yes',
                'role' => 'admin',
                'permissions' => [],
            ],
            [
                'name' => 'Ms. User',
                'designation' => 'USER',
                'email' => 'user@example.com',
                'password' => 'password',
                'is_super_admin' => 'No',
                'is_active' => 'Yes',
                'role' => 'user',
                'permissions' => [
                    'goods-receipt-note-list',
                    'goods-receipt-note-create',
                    'goods-receipt-note-edit',
                    'goods-receipt-note-post',
                    'goods-receipt-note-import',
                    'goods-receipt-note-view-own',
                    'goods-issue-list',
                    'goods-issue-create',
                    'goods-issue-edit',
                    'goods-issue-post',
                    'goods-issue-view-own',
                    'sales-settlement-list',
                    'sales-settlement-create',
                    'sales-settlement-edit',
                    'sales-settlement-post',
                    'sales-settlement-view-own',
                    'goods-issue-carton-entry',
                ],
            ],
            [
                'name' => 'WALEED',
                'designation' => 'KPO',
                'email' => 'wwaleedkhan742@gmail.com',
                'password' => 'password',
                'is_super_admin' => 'No',
                'is_active' => 'Yes',
                'role' => 'user',
                'permissions' => [
                    'goods-receipt-note-list',
                    'goods-receipt-note-create',
                    'goods-receipt-note-edit',
                    'goods-receipt-note-post',
                    'goods-receipt-note-import',
                    'goods-receipt-note-view-own',
                    'goods-issue-list',
                    'goods-issue-create',
                    'goods-issue-edit',
                    'goods-issue-post',
                    'goods-issue-view-own',
                    'sales-settlement-list',
                    'sales-settlement-create',
                    'sales-settlement-post',
                    'sales-settlement-view-own',
                    'goods-issue-carton-entry',
                ],
            ],
            [
                'name' => 'FARRUKH',
                'designation' => 'KPO',
                'email' => 'farrukhshah95mzd@gmail.com',
                'password' => 'password',
                'is_super_admin' => 'No',
                'is_active' => 'Yes',
                'role' => 'user',
                'permissions' => [
                    'goods-receipt-note-list',
                    'goods-receipt-note-create',
                    'goods-receipt-note-edit',
                    'goods-receipt-note-post',
                    'goods-receipt-note-import',
                    'goods-receipt-note-view-own',
                    'goods-issue-list',
                    'goods-issue-create',
                    'goods-issue-edit',
                    'goods-issue-post',
                    'goods-issue-view-own',
                    'sales-settlement-list',
                    'sales-settlement-create',
                    'sales-settlement-edit',
                    'sales-settlement-post',
                    'sales-settlement-view-own',
                    'inventory-view',
                    'goods-issue-carton-entry',
                ],
            ],
            [
                'name' => 'NOUMAN',
                'designation' => 'KPO',
                'email' => 'moon.traders.mzd@gmail.com',
                'password' => 'password',
                'is_super_admin' => 'No',
                'is_active' => 'No',
                'role' => 'user',
                'permissions' => [
                    'goods-receipt-note-list',
                    'goods-receipt-note-create',
                    'goods-receipt-note-edit',
                    'goods-receipt-note-post',
                    'goods-receipt-note-import',
                    'goods-receipt-note-view-own',
                    'goods-issue-list',
                    'goods-issue-create',
                    'goods-issue-edit',
                    'goods-issue-post',
                    'goods-issue-view-own',
                    'sales-settlement-list',
                    'sales-settlement-create',
                    'sales-settlement-edit',
                    'sales-settlement-post',
                    'sales-settlement-view-own',
                    'goods-issue-carton-entry',
                ],
            ],
            [
                'name' => 'ABDULLAH',
                'designation' => 'KPO',
                'email' => 'workflow317@gmail.com',
                'password' => 'password',
                'is_super_admin' => 'No',
                'is_active' => 'Yes',
                'role' => 'user',
                'permissions' => [
                    'goods-receipt-note-list',
                    'goods-receipt-note-create',
                    'goods-receipt-note-edit',
                    'goods-receipt-note-post',
                    'goods-receipt-note-import',
                    'goods-receipt-note-view-own',
                    'goods-issue-list',
                    'goods-issue-create',
                    'goods-issue-edit',
                    'goods-issue-post',
                    'goods-issue-view-own',
                    'sales-settlement-list',
                    'sales-settlement-create',
                    'sales-settlement-edit',
                    'sales-settlement-post',
                    'sales-settlement-view-own',
                    'goods-issue-carton-entry',
                ],
            ],
            [
                'name' => 'AKASH',
                'designation' => 'KPO',
                'email' => 'akashsheikhkashi925@gmail.com',
                'password' => 'password',
                'is_super_admin' => 'No',
                'is_active' => 'Yes',
                'role' => 'user',
                'permissions' => [
                    'goods-receipt-note-list',
                    'goods-receipt-note-create',
                    'goods-receipt-note-edit',
                    'goods-receipt-note-post',
                    'goods-receipt-note-import',
                    'goods-receipt-note-view-own',
                    'goods-issue-list',
                    'goods-issue-create',
                    'goods-issue-edit',
                    'goods-issue-post',
                    'goods-issue-view-own',
                    'sales-settlement-list',
                    'sales-settlement-create',
                    'sales-settlement-edit',
                    'sales-settlement-post',
                    'sales-settlement-view-own',
                    'goods-issue-carton-entry',
                ],
            ],
            [
                'name' => 'Waris Shah',
                'designation' => 'KPO',
                'email' => '69xshah@gmail.com',
                'password' => 'password',
                'is_super_admin' => 'No',
                'is_active' => 'Yes',
                'role' => 'user',
                'permissions' => [
                    'goods-receipt-note-list',
                    'goods-receipt-note-create',
                    'goods-receipt-note-edit',
                    'goods-receipt-note-post',
                    'goods-receipt-note-import',
                    'goods-receipt-note-view-own',
                    'goods-issue-list',
                    'goods-issue-create',
                    'goods-issue-edit',
                    'goods-issue-post',
                    'goods-issue-view-own',
                    'sales-settlement-list',
                    'sales-settlement-create',
                    'sales-settlement-edit',
                    'sales-settlement-post',
                    'sales-settlement-view-own',
                    'inventory-view',
                    'goods-issue-carton-entry',
                ],
            ],
        ];

        foreach ($users as $userData) {
            $user = User::updateOrCreate(
                ['email' => $userData['email']],
                [
                    'name' => $userData['name'],
                    'designation' => $userData['designation'],
                    'password' => $userData['password'],
                    'is_super_admin' => $userData['is_super_admin'],
                    'is_active' => $userData['is_active'],
                ]
            );

            if (Role::where('name', $userData['role'])->exists()) {
                $user->syncRoles([$userData['role']]);
            }

            if (! empty($userData['permissions'])) {
                $user->syncPermissions($userData['permissions']);
            }
        }
    }
}
