<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight inline-block">
            View Tax Transaction #{{ $transaction->id }}
        </h2>
        <div class="flex justify-center items-center float-right">
            <a href="{{ route('tax-transactions.index') }}"
                class="inline-flex items-center ml-2 px-4 py-2 bg-blue-950 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-green-800 focus:bg-green-800 active:bg-green-800 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition ease-in-out duration-150">
                <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                </svg>
            </a>
        </div>
    </x-slot>

    <div class="py-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-status-message class="mb-4 mt-4" />
                <div class="p-6">
                    <div class="bg-blue-50 border-l-4 border-blue-400 p-4 mb-6">
                        <p class="text-sm text-blue-700">
                            <strong>Note:</strong> Tax transactions are auto-generated by the system and cannot be edited directly.
                        </p>
                    </div>

                    <form>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <x-label for="tax_code" value="Tax Code" />
                                <x-input id="tax_code" type="text" name="tax_code"
                                    class="mt-1 block w-full cursor-not-allowed bg-gray-100"
                                    :value="$transaction->taxCode ? $transaction->taxCode->tax_code . ' - ' . $transaction->taxCode->name : 'N/A'"
                                    disabled readonly />
                            </div>

                            <div>
                                <x-label for="transaction_date" value="Transaction Date" />
                                <x-input id="transaction_date" type="text" name="transaction_date"
                                    class="mt-1 block w-full cursor-not-allowed bg-gray-100"
                                    :value="$transaction->transaction_date?->format('Y-m-d') ?? 'N/A'" disabled readonly />
                            </div>
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4">
                            <div>
                                <x-label for="taxable_amount" value="Taxable Amount" />
                                <x-input id="taxable_amount" type="text" name="taxable_amount"
                                    class="mt-1 block w-full cursor-not-allowed bg-gray-100"
                                    :value="number_format($transaction->taxable_amount, 2)" disabled readonly />
                            </div>

                            <div>
                                <x-label for="tax_rate" value="Tax Rate (%)" />
                                <x-input id="tax_rate" type="text" name="tax_rate"
                                    class="mt-1 block w-full cursor-not-allowed bg-gray-100"
                                    :value="number_format($transaction->tax_rate, 2) . '%'" disabled readonly />
                            </div>

                            <div>
                                <x-label for="tax_amount" value="Tax Amount" />
                                <x-input id="tax_amount" type="text" name="tax_amount"
                                    class="mt-1 block w-full cursor-not-allowed bg-gray-100 font-semibold"
                                    :value="number_format($transaction->tax_amount, 2)" disabled readonly />
                            </div>
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                            <div>
                                <x-label for="tax_direction" value="Tax Direction" />
                                <x-input id="tax_direction" type="text" name="tax_direction"
                                    class="mt-1 block w-full cursor-not-allowed bg-gray-100"
                                    :value="ucfirst($transaction->tax_direction)" disabled readonly />
                            </div>

                            <div>
                                <x-label for="tax_rate_used" value="Tax Rate Used" />
                                <x-input id="tax_rate_used" type="text" name="tax_rate_used"
                                    class="mt-1 block w-full cursor-not-allowed bg-gray-100"
                                    :value="$transaction->taxRate ? 'Rate ID: ' . $transaction->taxRate->id . ' (' . number_format($transaction->taxRate->rate, 2) . '%)' : 'N/A'"
                                    disabled readonly />
                            </div>
                        </div>

                        <div class="grid grid-cols-1 gap-4 mt-4">
                            <div>
                                <x-label for="source" value="Source Transaction" />
                                <x-input id="source" type="text" name="source"
                                    class="mt-1 block w-full cursor-not-allowed bg-gray-100"
                                    :value="class_basename($transaction->taxable_type) . ' #' . $transaction->taxable_id"
                                    disabled readonly />
                            </div>
                        </div>

                        <div class="flex items-center justify-between mt-6">
                            <div class="text-sm text-gray-500">
                                Created: {{ $transaction->created_at?->format('Y-m-d H:i:s') }}<br>
                                Updated: {{ $transaction->updated_at?->format('Y-m-d H:i:s') }}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
