{{-- Tax transactions are auto-generated and do not have editable form fields --}}
<div class="bg-yellow-50 border-l-4 border-yellow-400 p-4">
    <p class="text-sm text-yellow-700">
        <strong>Note:</strong> Tax transactions are auto-generated by the system and cannot be created or edited manually.
    </p>
</div>
