<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTaxTransactionRequest;
use App\Http\Requests\UpdateTaxTransactionRequest;
use App\Models\TaxCode;
use App\Models\TaxTransaction;
use Illuminate\Http\Request;
use Spatie\QueryBuilder\AllowedFilter;
use Spatie\QueryBuilder\QueryBuilder;

class TaxTransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $transactions = QueryBuilder::for(TaxTransaction::query())
            ->with(['taxCode', 'taxRate', 'taxable'])
            ->allowedFilters([
                AllowedFilter::exact('tax_code_id'),
                AllowedFilter::exact('tax_direction'),
                AllowedFilter::scope('date_from', 'dateFrom'),
                AllowedFilter::scope('date_to', 'dateTo'),
            ])
            ->orderBy('transaction_date', 'desc')
            ->orderBy('id', 'desc')
            ->paginate(10)
            ->withQueryString();

        $taxCodes = TaxCode::where('is_active', true)->orderBy('tax_code')->get();

        return view('settings.tax-transactions.index', [
            'transactions' => $transactions,
            'taxCodes' => $taxCodes,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        // Tax transactions are typically auto-generated by the system
        abort(404);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreTaxTransactionRequest $request)
    {
        // Tax transactions are typically auto-generated by the system
        abort(404);
    }

    /**
     * Display the specified resource.
     */
    public function show(TaxTransaction $taxTransaction)
    {
        $taxTransaction->load(['taxCode', 'taxRate', 'taxable']);

        return view('settings.tax-transactions.show', [
            'transaction' => $taxTransaction,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(TaxTransaction $taxTransaction)
    {
        // Tax transactions are typically auto-generated and should not be edited
        abort(404);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateTaxTransactionRequest $request, TaxTransaction $taxTransaction)
    {
        // Tax transactions are typically auto-generated and should not be edited
        abort(404);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(TaxTransaction $taxTransaction)
    {
        // Tax transactions should not be deleted directly
        abort(404);
    }
}
